<?php
// Last Updated 07 Nov 
// Continue the session
session_start();

echo "        
This Exported Data is Generated by IshuDbAdmin [Version .: 1.0.1]
Download the OpenSource Project from Github https://www.github.com/ishuweb/ishudbadmin
Date .: " . date("d/m/y") . "

";

if(isset($_POST['f-export-cur-dbname']) &&
   isset($_POST['f-export-cur-tbname'])
   )
  if (
    // check is login session var set
    isset($_SESSION['s-username']) &&
    isset($_SESSION['s-hostname']) &&
    isset($_SESSION['s-password'])
     )
    {
    // validate and save in local variable
    $cur_dbname = $_POST['f-export-cur-dbname'];
    $cur_tbname = $_POST['f-export-cur-tbname'];
    $username = $_SESSION['s-username'];
    $hostname = $_SESSION['s-hostname'];
    $password = $_SESSION['s-password']; 
        
    csv($username,$hostname,$password,$cur_dbname,$cur_tbname);
}

// function will export csv file
function csv($username,$hostname,$password,$cur_dbname,$cur_tbname) {

    try {
        // establish connection
        $con_1 = new mysqli($hostname, $username, $password, $cur_dbname);

        // sql statement
        $query_1 = "DESC" . " " . $cur_tbname . " ;";

        // run query
        try {
            $result_1 = $con_1->query($query_1);

            if($result_1-> num_rows > 0) {
                // declare a empty array
                $array_cols = array();
                // fill array until fethcing
                while($cols = $result_1->fetch_assoc()) {
                    // fill this var of every cycle
                    $val = $cols['Field'];
                    // push this var in empty array
                    array_push($array_cols,$val);
                }
            }
        }
        catch(EXCEPTION $error) {
            $error_messsage_2 = $error->getMessage();
            echo "<script>
            alert('{$error_messsage_2}');
            </script>";
        }
    }
    catch(EXCEPTION $error) {
        $error_messsage_1 = $error->getMessage();
        echo "<script>
        alert('{$error_messsage_1}');
        </script>";
    }

    try {
        // establish connection
        $con_2 = new mysqli($hostname, $username, $password, $cur_dbname);
        // create unique name for each file
        $name = "ishudbadmin_exported_file_" . date("d/m/y") . ".csv";
        // implode that array contain fields
        $columns = implode(",", $array_cols);
        echo $columns;
        // headers will tell type and charset of content
        header('Content-Type: text/csv; charset=utf-8');
        // header will ask browser to download file with $name name
        header("Content-Disposition: attachment; filename=$name");
        // export data will open
        $output = fopen("php://output", "w");
        // put heading in each columns but it will concentrate in one cell so print above echo $column
        fputcsv($output, array());

        // query
        $query_2 = "SELECT * FROM" . " " . $cur_tbname . " ;";
        // run query
        try {
            $result_2 = $con_2->query($query_2);
            if($result_2 ->num_rows > 0) {
                while($data = $result_2->fetch_assoc()) {
                    // put data in excel 
                    fputcsv($output, $data);
                }
            // close file
            fclose($output);
            }
        }
        catch(EXCEPTION $error) {
            $error_messsage_4 = $error->getMessage();
            echo "<script>
            alert('{$error_messsage_4}');
            </script>";
        }
    }
    catch(EXCEPTION $error) {
        $error_messsage_3 = $error->getMessage();
        echo "<script>
        alert('{$error_messsage_3}');
        </script>";
    }
}

?>

<script>
     if(!navigator.onLine) {
       alert("Ohh you're not connected to the Internet!");
       location.href="../";
        
     }
</script>

<noscript> 
        <div 
        style="position: fixed; top: 0; left:0; width:100%; height: 100vh; 
        background-color: rgb(255, 255, 255); z-index: 2000;
        display: flex; justify-content:center; align-items: center;">
        <h1 style="background-color: rgb(246, 167, 167); border-radius: 10px; padding: 10px; font-size: 30px;"> Please Enable Your Browser's Javascript Engine! </h1>
        </div>
</noscript>
